### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by choichoisum** [vdavid/node-mautic#12]
Hello @vdavid 

I am trying to connect mautic through API but not successful. Can you please help?

I also used axios to test but not successful. The only thing it works is to make request via curl.
```
curl -v -X GET https://username:password@--url--
```

Below is my code

```
const mauticConnector = require('node-mautic');

let mautic = new mauticConnector({
    apiUrl: "--url--",
    username: "username",
    password: "password",
    timeoutInSeconds: 10
})

mautic.contacts.listContacts().then((res) => {
    
    console.log("Successful")
    console.log(res)

}).catch((err) => {
    console.log("Error: " + err)
})
```

Here is the response:
```
Error: FetchError: request to https://-- url --/api/contacts failed, reason: connect ECONNREFUSED 174.138.0.0:443
```
Thank you

**Comment by choichoisum** [comment]
Hello @vdavid 

It turned out the cache issue. I am closing it. Thank you.

**Comment by vdavid** [comment]
Ah, great that it solved itself. I'm happy that it works now. :)
