### ISSUE TITLE
Error log throws error mapping errors

### ISSUE THREAD

**Issue by Sicria** [vdavid/node-mautic#2]
Is it possible to add a config flag of maybe ``verbose`` or ``debug`` to prevent console logs?

It's also currently causing an error due to the ``.map`` failing on the error object.

Quick fix would be to add multiple options but this could be made even safer with a type check before attempting to map.

```
const logMessage = 'MAUTIC | Mautic API error. | ' + (body.errors || result.errors || []).map(error => error.code + ': ' + error.message).join(', ');
console.log(logMessage);
throw new Error(logMessage);
```

Currently, I've just wrapped all requests in a try/catch to prevent bubbling up the stack, but this means I lose any context about an error which is not ideal.

**Comment by vdavid** [comment]
Thanks for your report. :)
Added a `logLevel` option plus added type checking for the error before mapping.
Version is now 1.0.2

**Comment by Sicria** [comment]
Thanks @vdavid appreciate the quick fix.
