### ISSUE TITLE
Mautic API Error with no additional information

### ISSUE THREAD

**Issue by Dmitri801** [vdavid/node-mautic#3]
Hi there, I'm running into the error 
```
MAUTIC | Mautic API error. | 
 Error: MAUTIC | Mautic API error. | 
at MauticConnector._callApi (/Users/djshine/Desktop/Side/cm-master/node_modules/node-mautic/MauticConnector.js:97:19)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

When making any API call, I have tried to change the `logLevel` to both `error` and 'verbose' and I don't receive any other log information on what this error is. I'm guessing this is related with the authentication since none of the requests are working - i'm positive the config is correct in terms of the mautic domain and the username and password

Here is a safe version of the MauticConnector object: 
```
const mauticConnector = new MauticConnector({ apiUrl: "https://mautic.chosenmasters.com", username: "dj", password: "123456", enableErrorLogging: true, logLevel: 'error' });

```

I am trying this from localhost would that make any difference? 

I appreciate any help, thanks!

**Comment by vdavid** [comment]
It should work from localhost, I've run it from localhost many times. The weird part is that you're not getting any error message after "MAUTIC | Mautic API error. | ". The error code and message should be after the second pipe character. Do you have line-to-line debugging? If you put a breakpoint to `/Users/djshine/Desktop/Side/cm-master/node_modules/node-mautic/MauticConnector.js:97` you could look at the `result` object itself and it would give you more info. That's what I'd do to get more info.
Also, sorry for the late response.

**Comment by Dmitri801** [comment]
Hey I appreciate the response, Turns out I had to clear the cache on the Mautic server, everything is working now. Thanks!
